/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testReadFromFile() {
        String testFile_ReadFromPath = "./src/main/resources/testFile_ReadFrom.json";
        try {
            assertEquals("Method should return the targeted quote and author from the test file.",
                    "Quotes{author='Marilyn Monroe', text='I am good, but not an angel. I do sin, but I am not the devil. I am just a small girl in a big world trying to find someone to love.', tags=[attributed-no-source], likes='18651 likes'}",
                    QuotesNoNet.readFromFile(testFile_ReadFromPath));
        } catch(Exception error){fail();}
    }

}
