/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.Reader;
import java.util.Random;

public class App {
    public static void main(String[] args) throws FileNotFoundException {
        Gson gson = new Gson();
        Reader reader = new FileReader("./app/src/main/resources/recentquotes.json");
        Quotes []convertedObject = gson.fromJson(reader, Quotes[].class);
        Random rand =new Random();
        int ranNum=rand.nextInt((convertedObject.length)+1);
        System.out.println(gson.toJson(convertedObject[ranNum]));

    }
}
